// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBgC1Vq2d9dYonoNVdkkwMI1tZQmpK0ek',
    appId: '1:131857091064:android:1d58319fe32520d6bbae0d',
    messagingSenderId: '131857091064',
    projectId: 'task-app-3fbc8',
    databaseURL: 'https://task-app-3fbc8-default-rtdb.firebaseio.com',
    storageBucket: 'task-app-3fbc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACac0oTRdHy_MWSTkiT6392DmNf0tB_xQ',
    appId: '1:131857091064:ios:00778f148bd0e880bbae0d',
    messagingSenderId: '131857091064',
    projectId: 'task-app-3fbc8',
    databaseURL: 'https://task-app-3fbc8-default-rtdb.firebaseio.com',
    storageBucket: 'task-app-3fbc8.appspot.com',
    androidClientId: '131857091064-v60385bkfu0of8uqomcqhq4f3ubpiosq.apps.googleusercontent.com',
    iosClientId: '131857091064-9uupv9r2rsa9bti5d0l86f2bg309en8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopzen',
  );
}
